# Generated by Django 4.1.7 on 2023-06-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_question', models.TextField()),
                ('data_context', models.TextField()),
            ],
        ),
    ]
