# Generated by Django 4.1.7 on 2023-06-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
