# Generated by Django 4.1.7 on 2023-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('url', models.TextField()),
                ('content', models.TextField()),
                ('voteup', models.TextField()),
                ('retweet', models.TextField()),
                ('comment', models.TextField()),
                ('specialty', models.TextField()),
                ('origin', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
