# Generated by Django 4.1.7 on 2023-06-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_data_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
